UpdateTrackInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
      position:
        type: "Int!"
      length:
        type: "Int!"
      album:
        type: "String!"