version: "3"

services:
  nginx:
    build: ./docker/nginx
    container_name: graphql_demo_nginx
    ports:
      - 127.0.0.101:80:80
    volumes:
      - ./app:/opt/app
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: graphql_demo_php
    volumes:
      - ./app:/opt/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: graphql_demo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql_demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./docker/data/db:/var/lib/mysql
